---
- name: Check tmp folder still there
  stat:
    path: "{{ mysql_vars['results'][2]['msg'][0][1] }}"
  register: check_tmp
  failed_when: False

- name: Create tmp folder if doesn't exist
  file:
    name: "{{ mysql_vars['results'][2]['msg'][0][1] }}"
    owner: mysql
    group: mysql
    state: directory
  when: check_tmp.stat.exists == 0

#- name: Remove folder if symlink
#  file:
#    path: "{{ mysql_vars['results'][0]['msg'][0][1][:-1] }}"
#    state: absent
#  when: datadir_symlink.stat.islnk

- name: Rename folder if symlink
  shell: mv {{ mysql_vars['results'][0]['msg'][0][1] }} {{ mysql_vars['results'][0]['msg'][0][1][:-1] }}.$(date +"%y%m%d-%H%M%S")
  when: datadir_symlink.stat.islnk

- name: Set real_path if symlink
  file:
    src: "{{ datadir_symlink['stat']['lnk_source'] }}"
    dest: "{{ mysql_vars['results'][0]['msg'][0][1][:-1] }}"
    state: link
  when: datadir_symlink.stat.islnk
