---
- name: Check if EPEL is installed
  shell: yum repolist | egrep -i epel | awk '{print $1}'
  register: epel_repo
  failed_when: false

- name: Check if IUS is installed
  shell: yum repolist | egrep -i ius | awk '{print $1}'
  register: ius_repo
  failed_when: false

- name: install EPEL release package for RHEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: latest
  when: epel_repo|failed

- set_fact:
    ius_distribution_abbrev: "{{ (ansible_distribution == 'CentOS') | ternary('centos', 'rhel') }}"

# Must be state: present due to deficiency in ansible. See:
# https://github.com/ansible/ansible-modules-core/issues/948
- name: install IUS release package
  yum:
    name: "https://{{ ius_distribution_abbrev }}{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm"
    state: present
  when: ius_repo|failed