---
- name: Add IUS when 7
  include: ius.yml
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Remove old MariaDB packages
  include: remove.yml

- name: Install MariaDB 10.0 from IUS on 7
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb100u
    - mariadb100u-server
    - mariadb100u-libs
  when: ansible_distribution_major_version == "7"

- name: Update my.cnf
  shell: cp -a /etc/my.cnf56 "{{ my_cnf }}"

- name: Install MariaDB from Maria repo
  include: mariadb.yml
  when: ansible_distribution_major_version == "6"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "10.0"


