---
- name: Remove old MariaDB packages
  include: remove.yml

- name: Install MariaDB 10.1 from IUS on 7
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb101u
    - mariadb101u-server
    - mariadb101u-libs
  when: ansible_distribution_major_version == "7"

- name: Set repo for Maria
  set_fact:
    repo: "10.1"
  when: ansible_distribution_major_version in ["5", "6"]

- name: Install MariaDB from Maria repo
  include: mariadb.yml
  when: ansible_distribution_major_version in ["5", "6"]

- name: Update my.cnf
  shell: cp -a /etc/my.cnf56 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "10.0"
