---
- name: Upgrade my.cnf to 5.7
  shell: /root/dbsake upgrade-mycnf -c "{{ my_cnf }}" -t 5.7 > /etc/my.cnf57

- name: Remove old MySQL 5.6 packages
  shell: rpm -e --nodeps mysql56u mysql56u-server mysql56u-libs mysql56u-common

- name: Install MySQL 5.7 from IUS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql57u
    - mysql57u-server
    - mysql57u-libs

- name: Update my.cnf
  shell: cp -a /etc/my.cnf57 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.7"