---
- name: Upgrade my.cnf to 5.5
  shell: /root/dbsake upgrade-mycnf -c "{{ my_cnf }}" -t 5.5 > /etc/my.cnf55

- name: Remove old MySQL 5.1 packages
  shell: rpm -e --nodeps mysql mysql-server mysql-libs

- name: Install MySQL 5.5 from IUS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql55
    - mysql55-server
    - mysql55-libs
    - mysqlclient16

- name: Update my.cnf
  shell: cp -a /etc/my.cnf55 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.5"