---
- name: Upgrade my.cnf to 5.6
  shell: /root/dbsake upgrade-mycnf -c "{{ my_cnf }}" -t 5.6 > /etc/my.cnf56

- name: Remove old MySQL 5.5 packages
  shell: rpm -e --nodeps mysql55 mysql55-server mysql55-libs

- name: Install MySQL 5.6 from IUS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql56u
    - mysql56u-server
    - mysql56u-libs

- name: Update my.cnf
  shell: cp -a /etc/my.cnf56 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.6"
