---
- name: Upgrade Percona my.cnf to 5.6
  shell: python /root/upgrade_mysql_config.py --config "{{ my_cnf }}" --target 5.6 > /etc/my.cnf56

- name: Remove old Percona packages
  include: remove.yml

- name: Install Percona 5.6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-server-56
    - Percona-Server-client-56
    - Percona-Server-shared-56

- name: Update my.cnf
  shell: cp -a /etc/my.cnf56 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.6"