---
- name: Upgrade my.cnf
  include: upgrade_mycnf.yml

- name: Remove old Percona packages
  include: remove.yml

- name: Install Percona 5.7
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-server-57
    - Percona-Server-client-57
    - Percona-Server-shared-57

- name: Update my.cnf
  shell: cp -a /etc/ansible_my.cnf57 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.7"