---
- name: Upgrade Percona my.cnf to 5.5
  shell: /root/dbsake upgrade-mycnf -c "{{ my_cnf }}" -t 5.5 > /etc/my.cnf55

- name: Remove old Percona packages
  include: remove.yml

- name: Install Percona 5.5
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-server-55
    - Percona-Server-client-55
    - Percona-Server-shared-55

- name: Update my.cnf
  shell: cp -a /etc/my.cnf55 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.5"