---
- name: Upgrade my.cnf
  include: upgrade_mycnf.yml

- name: Remove old Percona packages
  include: remove.yml

- name: Install Percona 5.5
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-server-55
    - Percona-Server-client-55
    - Percona-Server-shared-55

- name: Update my.cnf
  shell: cp -a /home/rack/{{ticket_no}}/ansible_my.cnf55 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.5"