---
- name: Upgrade my.cnf
  include: upgrade_mycnf.yml

- name: Remove old Percona packages
  include: remove.yml

- name: Install Percona 5.6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - Percona-Server-server-56
    - Percona-Server-client-56
    - Percona-Server-shared-56

- name: Update my.cnf
  shell: cp -a /home/rack/{{ticket_no}}/ansible_my.cnf56 "{{ my_cnf }}"

- name: Run mysql_upgrade
  include: upgrade.yml

- name: Set mysql_version
  set_fact:
    mysql_version: "5.6"