---
- name: Stop MySQL service to remove the packages
  service:
    name: "{{ mysql_service_name }}"
    state: stopped

- name: Remove old packages
  shell: rpm -e --nodeps $(rpm -qa | egrep "(^mysql-|^mysql51-|^mysql55-|^mysql56u-|^Percona-Server-|^MariaDB-|^mariadb)" | tee -a /home/rack/{{ticket_no}}/mysql_upgrade_rpm.txt) ; echo "####" >> /home/rack/{{ticket_no}}/mysql_upgrade_rpm.txt

- name: Remove mysqclient15 from RHEL5
  shell: rpm -e --nodeps mysqlclient15
  when: ansible_distribution_major_version == "5"
  failed_when: False
