---
- name: Backup existing my.cnf
  shell: cp -aL "{{ my_cnf }}" /etc/my.cnf.$(date +%Y%m%d)
  tags: upgrade_mycnf

- name: Upgrade 5.1 to 5.5
  shell: python /root/upgrade_mysql_config.py --config "{{ my_cnf }}" --target 5.5 > /etc/my.cnf55
  when: mysql_version.startswith("5.1") or (upgraded_version in [10.0, 10.1])
  tags: upgrade_mycnf

- name: Upgrade 5.5 to 5.6
  shell: python /root/upgrade_mysql_config.py --config "{{ my_cnf }}" --target 5.6 > /etc/my.cnf56
  when: mysql_version.startswith("5.5")
  tags: upgrade_mycnf

- name: Upgrade 5.6 to 5.7
  shell: python /root/upgrade_mysql_config.py --config "{{ my_cnf }}" --target 5.7 > /etc/my.cnf57
  when: mysql_version.startswith("5.6")
  tags: upgrade_mycnf